version: "2"

services:
  server:
    command: python src/server.py
    env_file:
      - .env
    image: python:3.4-jessie
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - "5044:5044"
    environment:
      MY_CELLAR_DB_CONTAINER: db
      MY_CELLAR_DB_PW: ""
      MY_CELLAR_DB_USER: root
      MY_CELLAR_PORT: 5044
      IMPORT_PATH: /mnt/test/fixture
      PYTHONPATH: $PYTHONPATH:src
      PYTHONUSERBASE: /mnt/vendor
      SERVICE_LOG: server.log

  db:
    command: mysqld --character-set-server=utf8 --sql_mode="ANSI,ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: my_cellar
    image: mysql:5.7.16
    volumes:
      - /var/lib/mysql

  testserver:
    command: python -m pytest $TEST_PATH
    environment:
      PYTHONPATH: $PYTHONPATH:src:test
      PYTHONUSERBASE: /mnt/vendor
      MY_CELLAR_DB_CONTAINER: testdb
      MY_CELLAR_DB_USER: root
      MY_CELLAR_PORT: 5053
    image: python:3.4-jessie
    depends_on:
      - testdb
    ports:
      - 5053:5053
    volumes:
      - .:/mnt
    working_dir: /mnt

  testdb:
    command: mysqld --character-set-server=utf8 --sql_mode="ANSI,ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: my_cellar
    image: mysql:5.7.16
